"""Karigar full-stack starter: persistent SQLite API and static website."""
from __future__ import annotations

import hashlib
import hmac
import json
import mimetypes
import os
import re
import secrets
import sqlite3
import time
import uuid
import base64
from collections import defaultdict, deque
import urllib.error
import urllib.request
from datetime import date, datetime
from http import cookies
from http.server import BaseHTTPRequestHandler, ThreadingHTTPServer
from pathlib import Path
from urllib.parse import unquote, urlparse

ROOT = Path(__file__).resolve().parent


def load_local_env():
    """Read ignored local .env values for the simple Windows run.bat workflow."""
    env_file = ROOT / ".env"
    if not env_file.is_file():
        return
    for line in env_file.read_text(encoding="utf-8").splitlines():
        line = line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, value = line.split("=", 1)
        key = key.strip()
        value = value.strip().strip("\"'")
        if key and key.replace("_", "").isalnum():
            os.environ.setdefault(key, value)


load_local_env()
STORAGE = Path(os.environ.get("KARIGAR_STORAGE", str(ROOT)))
DATA = STORAGE / "data"
UPLOADS = STORAGE / "uploads"
DB = DATA / "karigar.sqlite3"
DATABASE_URL = os.environ.get("DATABASE_URL", "").strip()
SUPABASE_URL = os.environ.get("SUPABASE_URL", "").rstrip("/")
SUPABASE_SERVICE_KEY = os.environ.get("SUPABASE_SERVICE_ROLE_KEY", "")
SUPABASE_BUCKET = os.environ.get("SUPABASE_STORAGE_BUCKET", "karigar-products")
HOST = os.environ.get("KARIGAR_HOST", "0.0.0.0")
PORT = int(os.environ.get("PORT", os.environ.get("KARIGAR_PORT", "8000")))
COOKIE = "karigar_session"
MAX_BODY = 8 * 1024 * 1024
COOKIE_SECURE = os.environ.get("KARIGAR_SECURE_COOKIE", "false").lower() == "true"
RATE_LIMITS = defaultdict(deque)


def connect():
    if DATABASE_URL:
        try:
            import psycopg
            from psycopg.rows import dict_row
        except ImportError as exc:
            raise RuntimeError("Install the production requirements before using DATABASE_URL.") from exc
        raw = psycopg.connect(DATABASE_URL, row_factory=dict_row)
        return PostgresConnection(raw)
    DATA.mkdir(exist_ok=True)
    db = sqlite3.connect(DB)
    db.row_factory = sqlite3.Row
    db.execute("PRAGMA foreign_keys = ON")
    return db


class PostgresConnection:
    """Small adapter so the same parameterized queries work with SQLite and Postgres."""
    def __init__(self, raw):
        self.raw = raw

    def __enter__(self):
        return self

    def __exit__(self, exc_type, exc, tb):
        try:
            if exc_type:
                self.raw.rollback()
            else:
                self.raw.commit()
        finally:
            self.raw.close()

    def execute(self, statement, params=()):
        if statement == "PRAGMA foreign_keys = ON":
            return None
        if statement == "BEGIN IMMEDIATE":
            statement = "BEGIN"
        return self.raw.execute(statement.replace("?", "%s"), params)


def initialize():
    if DATABASE_URL:
        if not SUPABASE_URL or not SUPABASE_SERVICE_KEY:
            raise RuntimeError("Hosted mode needs SUPABASE_URL and SUPABASE_SERVICE_ROLE_KEY for shared product photos.")
        with connect() as db:
            db.execute("""
            CREATE TABLE IF NOT EXISTS users (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                name TEXT NOT NULL, email TEXT NOT NULL UNIQUE,
                password_hash TEXT NOT NULL, role TEXT NOT NULL CHECK(role IN ('artisan','buyer')),
                location TEXT NOT NULL DEFAULT '', upi_id TEXT NOT NULL DEFAULT '', phone TEXT NOT NULL DEFAULT '', public_address TEXT NOT NULL DEFAULT '', show_contact BOOLEAN NOT NULL DEFAULT FALSE, created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
            )
            """)
            db.execute("ALTER TABLE users ADD COLUMN IF NOT EXISTS upi_id TEXT NOT NULL DEFAULT ''")
            db.execute("ALTER TABLE users ADD COLUMN IF NOT EXISTS phone TEXT NOT NULL DEFAULT ''")
            db.execute("ALTER TABLE users ADD COLUMN IF NOT EXISTS public_address TEXT NOT NULL DEFAULT ''")
            db.execute("ALTER TABLE users ADD COLUMN IF NOT EXISTS show_contact BOOLEAN NOT NULL DEFAULT FALSE")
            db.execute("CREATE UNIQUE INDEX IF NOT EXISTS users_email_lower_idx ON users (LOWER(email))")
            db.execute("""
            CREATE TABLE IF NOT EXISTS sessions (
                token_hash TEXT PRIMARY KEY, user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
                expires_at BIGINT NOT NULL
            )
            """)
            db.execute("""
            CREATE TABLE IF NOT EXISTS products (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                seller_id BIGINT NOT NULL REFERENCES users(id), name TEXT NOT NULL, category TEXT NOT NULL,
                price BIGINT NOT NULL CHECK(price > 0), description TEXT NOT NULL DEFAULT '',
                image_path TEXT NOT NULL DEFAULT '', stock INTEGER NOT NULL DEFAULT 1 CHECK(stock > 0),
                is_active BOOLEAN NOT NULL DEFAULT TRUE,
                created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
            )
            """)
            db.execute("ALTER TABLE products ADD COLUMN IF NOT EXISTS is_active BOOLEAN NOT NULL DEFAULT TRUE")
            db.execute("""
            CREATE TABLE IF NOT EXISTS orders (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                product_id BIGINT NOT NULL REFERENCES products(id), buyer_id BIGINT NOT NULL REFERENCES users(id),
                seller_id BIGINT NOT NULL REFERENCES users(id), quantity INTEGER NOT NULL CHECK(quantity > 0),
                total BIGINT NOT NULL CHECK(total > 0), status TEXT NOT NULL DEFAULT 'New',
                created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                delivery_phone TEXT NOT NULL DEFAULT '', delivery_address TEXT NOT NULL DEFAULT '',
                payment_order_id TEXT UNIQUE, payment_id TEXT UNIQUE,
                payment_status TEXT NOT NULL DEFAULT 'Demo', payment_expires_at BIGINT
            )
            """)
            db.execute("ALTER TABLE orders ADD COLUMN IF NOT EXISTS delivery_phone TEXT NOT NULL DEFAULT ''")
            db.execute("ALTER TABLE orders ADD COLUMN IF NOT EXISTS delivery_address TEXT NOT NULL DEFAULT ''")
            db.execute("ALTER TABLE orders ADD COLUMN IF NOT EXISTS payment_order_id TEXT UNIQUE")
            db.execute("ALTER TABLE orders ADD COLUMN IF NOT EXISTS payment_id TEXT UNIQUE")
            db.execute("ALTER TABLE orders ADD COLUMN IF NOT EXISTS payment_status TEXT NOT NULL DEFAULT 'Demo'")
            db.execute("ALTER TABLE orders ADD COLUMN IF NOT EXISTS payment_expires_at BIGINT")
            db.execute("CREATE TABLE IF NOT EXISTS payment_webhook_events (event_id TEXT PRIMARY KEY, created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP)")
            db.execute("CREATE INDEX IF NOT EXISTS products_category_idx ON products(category)")
            db.execute("CREATE INDEX IF NOT EXISTS orders_seller_idx ON orders(seller_id, created_at)")
            db.execute("CREATE INDEX IF NOT EXISTS orders_buyer_idx ON orders(buyer_id, created_at)")
        return
    with connect() as db:
        db.executescript("""
        CREATE TABLE IF NOT EXISTS users (
            id INTEGER PRIMARY KEY,
            name TEXT NOT NULL,
            email TEXT NOT NULL UNIQUE COLLATE NOCASE,
            password_hash TEXT NOT NULL,
            role TEXT NOT NULL CHECK(role IN ('artisan','buyer')),
            location TEXT NOT NULL DEFAULT '',
            upi_id TEXT NOT NULL DEFAULT '',
            phone TEXT NOT NULL DEFAULT '',
            public_address TEXT NOT NULL DEFAULT '',
            show_contact INTEGER NOT NULL DEFAULT 0,
            created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
        );
        CREATE TABLE IF NOT EXISTS sessions (
            token_hash TEXT PRIMARY KEY,
            user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
            expires_at INTEGER NOT NULL
        );
        CREATE TABLE IF NOT EXISTS products (
            id INTEGER PRIMARY KEY,
            seller_id INTEGER NOT NULL REFERENCES users(id),
            name TEXT NOT NULL,
            category TEXT NOT NULL,
            price INTEGER NOT NULL CHECK(price > 0),
            description TEXT NOT NULL DEFAULT '',
            image_path TEXT NOT NULL DEFAULT '',
            stock INTEGER NOT NULL DEFAULT 1 CHECK(stock > 0),
            is_active INTEGER NOT NULL DEFAULT 1,
            created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
        );
        CREATE TABLE IF NOT EXISTS orders (
            id INTEGER PRIMARY KEY,
            product_id INTEGER NOT NULL REFERENCES products(id),
            buyer_id INTEGER NOT NULL REFERENCES users(id),
            seller_id INTEGER NOT NULL REFERENCES users(id),
            quantity INTEGER NOT NULL CHECK(quantity > 0),
            total INTEGER NOT NULL CHECK(total > 0),
            status TEXT NOT NULL DEFAULT 'New',
            created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
            delivery_phone TEXT NOT NULL DEFAULT '', delivery_address TEXT NOT NULL DEFAULT '',
            payment_order_id TEXT UNIQUE, payment_id TEXT UNIQUE,
            payment_status TEXT NOT NULL DEFAULT 'Demo', payment_expires_at INTEGER
        );
        CREATE TABLE IF NOT EXISTS payment_webhook_events (
            event_id TEXT PRIMARY KEY, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
        );
        CREATE INDEX IF NOT EXISTS products_category_idx ON products(category);
        CREATE INDEX IF NOT EXISTS orders_seller_idx ON orders(seller_id, created_at);
        CREATE INDEX IF NOT EXISTS orders_buyer_idx ON orders(buyer_id, created_at);
        """)
        existing_users = {row[1] for row in db.execute("PRAGMA table_info(users)").fetchall()}
        if "upi_id" not in existing_users:
            db.execute("ALTER TABLE users ADD COLUMN upi_id TEXT NOT NULL DEFAULT ''")
        for column, definition in {
            "phone": "TEXT NOT NULL DEFAULT ''", "public_address": "TEXT NOT NULL DEFAULT ''",
            "show_contact": "INTEGER NOT NULL DEFAULT 0",
        }.items():
            if column not in existing_users:
                db.execute(f"ALTER TABLE users ADD COLUMN {column} {definition}")
        existing_products = {row[1] for row in db.execute("PRAGMA table_info(products)").fetchall()}
        if "is_active" not in existing_products:
            db.execute("ALTER TABLE products ADD COLUMN is_active INTEGER NOT NULL DEFAULT 1")
        existing = {row[1] for row in db.execute("PRAGMA table_info(orders)").fetchall()}
        for column, definition in {
            "delivery_phone": "TEXT NOT NULL DEFAULT ''", "delivery_address": "TEXT NOT NULL DEFAULT ''",
            "payment_order_id": "TEXT", "payment_id": "TEXT",
            "payment_status": "TEXT NOT NULL DEFAULT 'Demo'", "payment_expires_at": "INTEGER",
        }.items():
            if column not in existing:
                db.execute(f"ALTER TABLE orders ADD COLUMN {column} {definition}")
        db.execute("CREATE UNIQUE INDEX IF NOT EXISTS orders_payment_order_id_idx ON orders(payment_order_id)")
        db.execute("CREATE UNIQUE INDEX IF NOT EXISTS orders_payment_id_idx ON orders(payment_id)")


def password_hash(password: str) -> str:
    salt = secrets.token_bytes(16)
    digest = hashlib.scrypt(password.encode(), salt=salt, n=2**14, r=8, p=1)
    return salt.hex() + ":" + digest.hex()


def password_ok(password: str, saved: str) -> bool:
    try:
        salt_hex, digest_hex = saved.split(":", 1)
        digest = hashlib.scrypt(password.encode(), salt=bytes.fromhex(salt_hex), n=2**14, r=8, p=1)
        return hmac.compare_digest(digest.hex(), digest_hex)
    except (ValueError, TypeError):
        return False


class Handler(BaseHTTPRequestHandler):
    server_version = "Karigar/1.0"

    def log_message(self, fmt, *args):
        print("%s - %s" % (self.address_string(), fmt % args))

    def send_json(self, status, value, extra_headers=None):
        body = json.dumps(value, ensure_ascii=False, default=lambda item: item.isoformat() if isinstance(item, (date, datetime)) else str(item)).encode("utf-8")
        self.send_response(status)
        self.send_header("Content-Type", "application/json; charset=utf-8")
        self.send_header("Content-Length", str(len(body)))
        self.send_header("Cache-Control", "no-store")
        self.send_header("X-Content-Type-Options", "nosniff")
        self.send_header("Referrer-Policy", "strict-origin-when-cross-origin")
        self.send_header("X-Frame-Options", "DENY")
        self.send_header("Permissions-Policy", "camera=(), microphone=(self), geolocation=()")
        self.send_header("Content-Security-Policy", "default-src 'self'; script-src 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; font-src 'self' https://fonts.gstatic.com data:; img-src 'self' data: https:; connect-src 'self' https://*.supabase.co; base-uri 'self'; object-src 'none'; frame-ancestors 'none'; form-action 'self'")
        if COOKIE_SECURE:
            self.send_header("Strict-Transport-Security", "max-age=31536000; includeSubDomains")
        if extra_headers:
            for key, val in extra_headers.items():
                self.send_header(key, val)
        self.end_headers()
        self.wfile.write(body)

    def body_json(self):
        length = int(self.headers.get("Content-Length", "0"))
        if length > MAX_BODY:
            raise ValueError("Request is too large (8 MB max).")
        raw = self.rfile.read(length)
        try:
            data = json.loads(raw or b"{}")
        except json.JSONDecodeError as exc:
            raise ValueError("Please send valid form data.") from exc
        if not isinstance(data, dict):
            raise ValueError("Invalid request data.")
        return data

    def session_user(self, db):
        raw = self.headers.get("Cookie", "")
        jar = cookies.SimpleCookie()
        try:
            jar.load(raw)
            token = jar[COOKIE].value
        except (KeyError, cookies.CookieError):
            return None
        key = hashlib.sha256(token.encode()).hexdigest()
        row = db.execute("SELECT u.* FROM sessions s JOIN users u ON u.id=s.user_id WHERE s.token_hash=? AND s.expires_at>?", (key, int(time.time()))).fetchone()
        return dict(row) if row else None

    def require_user(self, db, role=None):
        user = self.session_user(db)
        if not user:
            self.send_json(401, {"error": "Please sign in first."})
            return None
        if role and user["role"] != role:
            self.send_json(403, {"error": f"Please sign in as a {role}."})
            return None
        return user

    def do_GET(self):
        parsed = urlparse(self.path)
        path = unquote(parsed.path)
        if path == "/healthz":
            self.send_json(200, {"ok": True})
            return
        if path.startswith("/api/"):
            self.api_get(path)
            return
        if path.startswith("/uploads/"):
            self.serve_upload(path)
            return
        if path == "/auth.html":
            self.serve_file(ROOT / "auth.html")
            return
        if path in ("/", "/index.html"):
            self.serve_file(ROOT / "index.html")
            return
        if path in ("/styles.css", "/app.js"):
            self.serve_file(ROOT / path.lstrip("/"))
            return
        self.send_error(404)

    def api_get(self, path):
        with connect() as db:
            if path == "/api/me":
                user = self.session_user(db)
                self.send_json(200, {"user": self.public_user(user) if user else None})
            elif path == "/api/profile/contact":
                user = self.require_user(db, "artisan")
                if not user:
                    return
                profile = db.execute("SELECT phone,public_address,show_contact FROM users WHERE id=?", (user["id"],)).fetchone()
                self.send_json(200, {"contact": dict(profile)})
            elif path == "/api/products":
                rows = db.execute("""SELECT p.*, u.name AS seller_name, u.location AS seller_location, CASE WHEN u.show_contact THEN u.phone ELSE '' END AS seller_phone, CASE WHEN u.show_contact THEN u.public_address ELSE '' END AS seller_public_address
                    FROM products p JOIN users u ON u.id=p.seller_id WHERE p.is_active AND p.stock>0 ORDER BY p.created_at DESC, p.id DESC""").fetchall()
                self.send_json(200, {"products": [dict(r) for r in rows]})
            elif path.startswith("/api/products/"):
                product_id = self.path_id(path, "/api/products/")
                row = db.execute("""SELECT p.*, u.name AS seller_name, u.location AS seller_location, u.upi_id AS seller_upi_id, CASE WHEN u.show_contact THEN u.phone ELSE '' END AS seller_phone, CASE WHEN u.show_contact THEN u.public_address ELSE '' END AS seller_public_address
                    FROM products p JOIN users u ON u.id=p.seller_id WHERE p.id=? AND p.is_active=TRUE
                AND p.stock>0""", (product_id,)).fetchone()
                if row:
                    self.send_json(200, {"product": dict(row)})
                else:
                    self.send_json(404, {"error": "That product could not be found."})
            elif path in ("/api/orders", "/api/my-products"):
                user = self.require_user(db)
                if not user:
                    return
                if path == "/api/my-products":
                    if user["role"] != "artisan":
                        self.send_json(403, {"error": "Artisan account required."})
                        return
                    rows = db.execute("SELECT * FROM products WHERE seller_id=? ORDER BY created_at DESC", (user["id"],)).fetchall()
                    self.send_json(200, {"products": [dict(r) for r in rows]})
                elif user["role"] == "artisan":
                    rows = db.execute("""SELECT o.*, p.name AS product_name, b.name AS buyer_name, b.email AS buyer_email
                        FROM orders o JOIN products p ON p.id=o.product_id JOIN users b ON b.id=o.buyer_id
                        WHERE o.seller_id=? ORDER BY o.created_at DESC, o.id DESC""", (user["id"],)).fetchall()
                    self.send_json(200, {"orders": [dict(r) for r in rows]})
                else:
                    rows = db.execute("""SELECT o.*, p.name AS product_name, s.name AS seller_name
                        FROM orders o JOIN products p ON p.id=o.product_id JOIN users s ON s.id=o.seller_id
                        WHERE o.buyer_id=? ORDER BY o.created_at DESC, o.id DESC""", (user["id"],)).fetchall()
                    self.send_json(200, {"orders": [dict(r) for r in rows]})
            else:
                self.send_json(404, {"error": "Not found."})

    @staticmethod
    def path_id(path, prefix):
        try:
            return int(path[len(prefix):])
        except ValueError:
            return -1

    @staticmethod
    def public_user(user):
        return {k: user[k] for k in ("id", "name", "email", "role", "location", "upi_id")}

    def do_POST(self):
        path = urlparse(self.path).path
        if not path.startswith("/api/"):
            self.send_json(404, {"error": "Not found."})
            return
        if not self.same_origin_request():
            self.send_json(403, {"error": "Please submit this request from the Karigar website."})
            return
        if not self.headers.get("Content-Type", "").lower().startswith("application/json"):
            self.send_json(415, {"error": "This endpoint accepts JSON requests only."})
            return
        if path in ("/api/login", "/api/signup") and self.rate_limited(path, 8, 300):
            self.send_json(429, {"error": "Too many attempts. Please wait a few minutes and try again."})
            return
        try:
            data = self.body_json()
            with connect() as db:
                if path == "/api/signup":
                    self.signup(db, data)
                elif path == "/api/login":
                    self.login(db, data)
                elif path == "/api/logout":
                    self.logout(db)
                elif path == "/api/products":
                    self.create_product(db, data)
                elif path == "/api/products/visibility":
                    self.set_product_visibility(db, data)
                elif path == "/api/profile/upi":
                    self.save_upi_profile(db, data)
                elif path == "/api/profile/contact":
                    self.save_contact_profile(db, data)
                elif path == "/api/upi-orders":
                    self.create_upi_order(db, data)
                elif path == "/api/cod-orders":
                    self.create_cod_order(db, data)
                elif path == "/api/orders/payment-confirm":
                    self.confirm_upi_payment(db, data)
                elif path == "/api/orders/cod-confirm":
                    self.confirm_cod_payment(db, data)
                elif path == "/api/orders/status":
                    self.update_order_status(db, data)
                else:
                    self.send_json(404, {"error": "Not found."})
        except ValueError as exc:
            self.send_json(400, {"error": str(exc)})
        except sqlite3.IntegrityError:
            self.send_json(409, {"error": "That email is already registered, or the request conflicts with current stock."})
        except Exception as exc:
            if exc.__class__.__name__ in ("UniqueViolation", "ForeignKeyViolation", "CheckViolation"):
                self.send_json(409, {"error": "That email is already registered, or the request conflicts with current stock."})
                return
            print("Request failed:", repr(exc))
            self.send_json(500, {"error": "Something went wrong. Please try again."})

    def same_origin_request(self):
        origin = self.headers.get("Origin")
        if not origin:
            return not DATABASE_URL
        parsed = urlparse(origin)
        if parsed.netloc.lower() != self.headers.get("Host", "").lower():
            return False
        forwarded_proto = self.headers.get("X-Forwarded-Proto", "").split(",")[0].strip().lower()
        expected_scheme = "https" if COOKIE_SECURE or forwarded_proto == "https" else "http"
        return parsed.scheme.lower() == expected_scheme

    def rate_limited(self, key, limit, seconds):
        now = time.time()
        bucket = RATE_LIMITS[f"{self.client_address[0]}:{key}"]
        while bucket and bucket[0] < now - seconds:
            bucket.popleft()
        if len(bucket) >= limit:
            return True
        bucket.append(now)
        return False

    def signup(self, db, data):
        name = str(data.get("name", "")).strip()[:80]
        email = str(data.get("email", "")).strip().lower()[:254]
        password = str(data.get("password", ""))
        role = data.get("role")
        location = str(data.get("location", "")).strip()[:100]
        if len(name) < 2 or not re.fullmatch(r"[^\s@]+@[^\s@]+\.[^\s@]+", email):
            raise ValueError("Enter your name and a valid email address.")
        if len(password) < 8:
            raise ValueError("Use a password with at least 8 characters.")
        if role not in ("artisan", "buyer"):
            raise ValueError("Choose an artisan or buyer account.")
        cur = db.execute("INSERT INTO users(name,email,password_hash,role,location) VALUES(?,?,?,?,?) RETURNING id", (name,email,password_hash(password),role,location))
        user = db.execute("SELECT * FROM users WHERE id=?", (cur.fetchone()["id"],)).fetchone()
        self.new_session(db, user)

    def login(self, db, data):
        email = str(data.get("email", "")).strip().lower()
        password = str(data.get("password", ""))
        row = db.execute("SELECT * FROM users WHERE email=?", (email,)).fetchone()
        if not row or not password_ok(password, row["password_hash"]):
            self.send_json(401, {"error": "Email or password didn’t match."})
            return
        self.new_session(db, row)

    def save_contact_profile(self, db, data):
        user = self.require_user(db, "artisan")
        if not user:
            return
        phone = str(data.get("phone", "")).strip()[:40]
        public_address = str(data.get("public_address", "")).strip()[:500]
        show_contact = data.get("show_contact") is True
        digits = re.sub(r"\D", "", phone)
        if phone and not 7 <= len(digits) <= 15:
            raise ValueError("Enter a valid mobile number with 7 to 15 digits.")
        if show_contact and not (phone or public_address):
            raise ValueError("Add a phone number or public business address before sharing contact details.")
        db.execute("UPDATE users SET phone=?,public_address=?,show_contact=? WHERE id=?", (phone, public_address, show_contact, user["id"]))
        self.send_json(200, {"ok": True, "show_contact": show_contact})

    def save_upi_profile(self, db, data):
        user = self.require_user(db, "artisan")
        if not user:
            return
        upi_id = str(data.get("upi_id", "")).strip()[:200]
        if upi_id and not re.fullmatch(r"[A-Za-z0-9._-]{2,128}@[A-Za-z0-9.-]{2,64}", upi_id):
            raise ValueError("Enter a valid UPI ID, such as name@bank.")
        db.execute("UPDATE users SET upi_id=? WHERE id=?", (upi_id, user["id"]))
        updated = db.execute("SELECT * FROM users WHERE id=?", (user["id"],)).fetchone()
        self.send_json(200, {"user": self.public_user(dict(updated))})

    def new_session(self, db, user):
        token = secrets.token_urlsafe(32)
        db.execute("INSERT INTO sessions(token_hash,user_id,expires_at) VALUES(?,?,?)", (hashlib.sha256(token.encode()).hexdigest(), user["id"], int(time.time()) + 60*60*24*14))
        secure = "; Secure" if COOKIE_SECURE else ""
        self.send_json(200, {"user": self.public_user(dict(user))}, {"Set-Cookie": f"{COOKIE}={token}; Path=/; HttpOnly; SameSite=Lax; Max-Age=1209600{secure}"})

    def logout(self, db):
        raw = self.headers.get("Cookie", "")
        jar = cookies.SimpleCookie()
        try:
            jar.load(raw)
            token = jar[COOKIE].value
            db.execute("DELETE FROM sessions WHERE token_hash=?", (hashlib.sha256(token.encode()).hexdigest(),))
        except (KeyError, cookies.CookieError):
            pass
        secure = "; Secure" if COOKIE_SECURE else ""
        self.send_json(200, {"ok": True}, {"Set-Cookie": f"{COOKIE}=; Path=/; HttpOnly; SameSite=Lax; Max-Age=0{secure}"})

    def create_product(self, db, data):
        user = self.require_user(db, "artisan")
        if not user:
            return
        name = str(data.get("name", "")).strip()[:120]
        category = str(data.get("category", "")).strip()[:50]
        description = str(data.get("description", "")).strip()[:3000]
        try:
            price = int(data.get("price", 0))
            stock = int(data.get("stock", 1))
        except (TypeError, ValueError):
            raise ValueError("Enter a valid price and stock quantity.")
        if len(name) < 2 or not category or price < 1 or price > 10000000 or stock < 1 or stock > 10000:
            raise ValueError("Add a product name, craft type, positive price, and available quantity.")
        image_path = self.save_image(data.get("image", ""))
        cur = db.execute("INSERT INTO products(seller_id,name,category,price,description,image_path,stock) VALUES(?,?,?,?,?,?,?) RETURNING id", (user["id"],name,category,price,description,image_path,stock))
        row = db.execute("SELECT p.*, u.name AS seller_name, u.location AS seller_location FROM products p JOIN users u ON u.id=p.seller_id WHERE p.id=?", (cur.fetchone()["id"],)).fetchone()
        self.send_json(201, {"product": dict(row)})

    def set_product_visibility(self, db, data):
        user = self.require_user(db, "artisan")
        if not user:
            return
        try:
            product_id = int(data.get("product_id", 0))
        except (TypeError, ValueError):
            raise ValueError("Choose a valid product.")
        active = data.get("is_active") is True
        product = db.execute("SELECT id, stock FROM products WHERE id=? AND seller_id=?", (product_id, user["id"])).fetchone()
        if not product:
            self.send_json(404, {"error": "That product could not be found in your shop."})
            return
        if active and product["stock"] < 1:
            raise ValueError("Add available stock before showing this listing again.")
        db.execute("UPDATE products SET is_active=? WHERE id=? AND seller_id=?", (active, product_id, user["id"]))
        self.send_json(200, {"ok": True, "is_active": active})

    def save_image(self, encoded):
        if not encoded:
            return ""
        match = re.fullmatch(r"data:(image/(?:jpeg|png|webp));base64,([A-Za-z0-9+/=]+)", str(encoded))
        if not match:
            raise ValueError("Use a JPG, PNG, or WebP product photo.")
        import base64
        try:
            raw = base64.b64decode(match.group(2), validate=True)
        except ValueError as exc:
            raise ValueError("That photo could not be read. Please choose another.") from exc
        if len(raw) > 5 * 1024 * 1024:
            raise ValueError("Please choose a photo smaller than 5 MB.")
        ext = {"image/jpeg":"jpg", "image/png":"png", "image/webp":"webp"}[match.group(1)]
        filename = uuid.uuid4().hex + "." + ext
        mime = match.group(1)
        if SUPABASE_URL and SUPABASE_SERVICE_KEY:
            url = f"{SUPABASE_URL}/storage/v1/object/{SUPABASE_BUCKET}/{filename}"
            request = urllib.request.Request(url, data=raw, method="POST", headers={
                "Authorization": f"Bearer {SUPABASE_SERVICE_KEY}",
                "apikey": SUPABASE_SERVICE_KEY,
                "Content-Type": mime,
                "x-upsert": "false",
            })
            try:
                with urllib.request.urlopen(request, timeout=20) as response:
                    if response.status not in (200, 201):
                        raise ValueError("Could not save the product photo. Please try again.")
            except (urllib.error.URLError, TimeoutError) as exc:
                raise ValueError("Could not save the product photo. Please try again.") from exc
            return f"{SUPABASE_URL}/storage/v1/object/public/{SUPABASE_BUCKET}/{filename}"
        UPLOADS.mkdir(exist_ok=True)
        (UPLOADS / filename).write_bytes(raw)
        return "/uploads/" + filename

    def create_upi_order(self, db, data):
        user = self.require_user(db, "buyer")
        if not user:
            return
        try:
            product_id = int(data.get("product_id", 0))
            quantity = int(data.get("quantity", 1))
        except (ValueError, TypeError):
            raise ValueError("Choose a valid product and quantity.")
        if quantity < 1 or quantity > 50:
            raise ValueError("Choose a quantity between 1 and 50.")
        product = db.execute("""SELECT p.*,u.name AS seller_name,u.upi_id AS seller_upi_id
            FROM products p JOIN users u ON u.id=p.seller_id WHERE p.id=?""", (product_id,)).fetchone()
        if not product or product["stock"] < quantity:
            raise ValueError("That quantity is no longer available.")
        if product["seller_id"] == user["id"]:
            raise ValueError("Use a separate buyer account to order your own listing.")
        if not product["seller_upi_id"]:
            raise ValueError("This artisan has not added a UPI ID yet. Please contact the artisan or try another product.")
        total = int(product["price"]) * quantity
        cur = db.execute("""INSERT INTO orders(product_id,buyer_id,seller_id,quantity,total,status,payment_status)
            VALUES(?,?,?,?,?,'Awaiting UPI payment','Pending UPI') RETURNING id""",
            (product_id,user["id"],product["seller_id"],quantity,total))
        order_id = cur.fetchone()["id"]
        self.send_json(201, {"order_id": order_id, "amount": total, "currency": "INR",
            "payee_vpa": product["seller_upi_id"], "payee_name": product["seller_name"],
            "product_name": product["name"], "quantity": quantity})

    def create_cod_order(self, db, data):
        user = self.require_user(db, "buyer")
        if not user:
            return
        try:
            product_id = int(data.get("product_id", 0))
            quantity = int(data.get("quantity", 1))
        except (ValueError, TypeError):
            raise ValueError("Choose a valid product and quantity.")
        if quantity < 1 or quantity > 50:
            raise ValueError("Choose a quantity between 1 and 50.")
        db.execute("BEGIN IMMEDIATE")
        product = db.execute("SELECT * FROM products WHERE id=?", (product_id,)).fetchone()
        if not product or product["stock"] < quantity:
            raise ValueError("That quantity is no longer available.")
        if product["seller_id"] == user["id"]:
            raise ValueError("Use a separate buyer account to order your own listing.")
        changed = db.execute("UPDATE products SET stock=stock-? WHERE id=? AND stock>=?", (quantity, product_id, quantity))
        if changed.rowcount != 1:
            raise ValueError("That quantity is no longer available.")
        total = int(product["price"]) * quantity
        cur = db.execute("""INSERT INTO orders(product_id,buyer_id,seller_id,quantity,total,status,payment_status)
            VALUES(?,?,?,?,?,'Confirmed','Cash on delivery') RETURNING id""",
            (product_id, user["id"], product["seller_id"], quantity, total))
        order_id = cur.fetchone()["id"]
        self.send_json(201, {"order_id": order_id, "amount": total, "currency": "INR",
            "product_name": product["name"], "quantity": quantity, "payment_status": "Cash on delivery"})

    def cancel_upi_order(self, db, data):
        user = self.require_user(db, "buyer")
        if not user:
            return
        try:
            order_id = int(data.get("order_id", 0))
        except (ValueError, TypeError):
            raise ValueError("Choose a valid order.")
        db.execute("""UPDATE orders SET payment_status='Cancelled',status='Payment cancelled'
            WHERE id=? AND buyer_id=? AND payment_status='Pending UPI'""", (order_id,user["id"]))
        self.send_json(200, {"ok": True})

    def confirm_upi_payment(self, db, data):
        user = self.require_user(db, "artisan")
        if not user:
            return
        try:
            order_id = int(data.get("order_id", 0))
        except (ValueError, TypeError):
            raise ValueError("Choose a valid order.")
        db.execute("BEGIN IMMEDIATE")
        order = db.execute("SELECT * FROM orders WHERE id=? AND seller_id=?", (order_id,user["id"])).fetchone()
        if not order:
            self.send_json(404, {"error": "That order could not be found."})
            return
        if order["payment_status"] not in ("Pending UPI", "Buyer reported"):
            self.send_json(409, {"error": "This UPI order is not awaiting artisan confirmation."})
            return
        changed = db.execute("UPDATE products SET stock=stock-? WHERE id=? AND stock>=?", (order["quantity"],order["product_id"],order["quantity"]))
        if changed.rowcount != 1:
            db.execute("UPDATE orders SET payment_status='Unavailable',status='Unavailable' WHERE id=?", (order_id,))
            self.send_json(409, {"error": "There is not enough stock left to confirm this order."})
            return
        db.execute("UPDATE orders SET payment_status='Paid (artisan confirmed)',status='New' WHERE id=?", (order_id,))
        self.send_json(200, {"ok": True})

    def confirm_cod_payment(self, db, data):
        user = self.require_user(db, "artisan")
        if not user:
            return
        try:
            order_id = int(data.get("order_id", 0))
        except (ValueError, TypeError):
            raise ValueError("Choose a valid order.")
        changed = db.execute("""UPDATE orders SET payment_status='Cash received'
            WHERE id=? AND seller_id=? AND status='Completed' AND payment_status='Cash on delivery'""",
            (order_id, user["id"]))
        if changed.rowcount != 1:
            self.send_json(409, {"error": "Mark the COD order completed after delivery before confirming cash."})
            return
        self.send_json(200, {"ok": True})

    def update_order_status(self, db, data):
        user = self.require_user(db, "artisan")
        if not user:
            return
        try:
            order_id = int(data.get("order_id", 0))
        except (TypeError, ValueError):
            raise ValueError("Choose a valid order.")
        next_status = str(data.get("status", ""))
        allowed = {"New": "Preparing", "Confirmed": "Preparing", "Preparing": "Shipped", "Shipped": "Completed"}
        row = db.execute("SELECT status FROM orders WHERE id=? AND seller_id=?", (order_id, user["id"])).fetchone()
        if not row:
            self.send_json(404, {"error": "That order could not be found."})
            return
        if allowed.get(row["status"]) != next_status:
            self.send_json(409, {"error": "Orders can move forward one step at a time."})
            return
        db.execute("UPDATE orders SET status=? WHERE id=? AND seller_id=?", (next_status, order_id, user["id"]))
        self.send_json(200, {"ok": True, "status": next_status})

    def serve_upload(self, path):
        filename = Path(path).name
        file_path = UPLOADS / filename
        if not re.fullmatch(r"[a-f0-9]{32}\.(?:jpg|png|webp)", filename) or not file_path.is_file():
            self.send_error(404)
            return
        self.serve_file(file_path)

    def serve_file(self, path):
        try:
            body = path.read_bytes()
        except OSError:
            self.send_error(404)
            return
        mime = mimetypes.guess_type(str(path))[0] or "application/octet-stream"
        self.send_response(200)
        self.send_header("Content-Type", mime + ("; charset=utf-8" if mime.startswith("text/") else ""))
        self.send_header("Content-Length", str(len(body)))
        self.send_header("Cache-Control", "no-cache")
        self.send_header("X-Content-Type-Options", "nosniff")
        self.send_header("Referrer-Policy", "strict-origin-when-cross-origin")
        self.send_header("X-Frame-Options", "DENY")
        self.send_header("Permissions-Policy", "camera=(), microphone=(self), geolocation=()")
        self.send_header("Content-Security-Policy", "default-src 'self'; script-src 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; font-src 'self' https://fonts.gstatic.com data:; img-src 'self' data: https:; connect-src 'self' https://*.supabase.co; base-uri 'self'; object-src 'none'; frame-ancestors 'none'; form-action 'self'")
        if COOKIE_SECURE:
            self.send_header("Strict-Transport-Security", "max-age=31536000; includeSubDomains")
        self.end_headers()
        self.wfile.write(body)


if __name__ == "__main__":
    initialize()
    print(f"Karigar is running at http://{HOST}:{PORT}")
    print("Press Ctrl+C to stop the local server.")
    ThreadingHTTPServer((HOST, PORT), Handler).serve_forever()
